version: '3.8'

services:
  # The Trading Bot Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  # The Analytics Dashboard Service
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      # Expose the dashboard on port 5001 of the host machine
      # Format is "HOST_PORT:CONTAINER_PORT"
      - "5001:5000"
    env_file:
      - .env

  # The PostgreSQL Database Service
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Expose the database port to the host machine for direct access if needed
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # This creates a persistent volume for the database data
  postgres_data:
